### ISSUE TITLE
Generic class for attune_delay like autonomics

### ISSUE THREAD

**Issue by kameyer226** [yaq-project/yaqd-attune#17]
A stripped down class similar to AttuneDelay but initializes with more instructions from a config file, attune catalog, and/or data file.   The attune_delay looks really good for an autonomic feature that changes an input angle to achieve a certain expected phasematching condition for a given set of frequency inputs,  but the current terminologies (`_kind="attune-delay" `, `class AttuneDelay`, specific traits) are specific to the word "delay".

Alternately,  separate kinds for each type of attune ( like "attune_theta",  "attune_theta_corrector" (a possible kinematic mirror to adjust errors between expected angle changes and an adjustment to get spatial overlap again, for example)), and just a series of streamlined code that generalizes the entire class constructor.

This class may be necessary in order to generate constant phasematching protocols for four-wave mixing work particularly at lower visible wavelengths where phasematching is more critical  (ie., cobalamins, metal carbonyls, paddlewheel complexes)

**Comment by untzag** [comment]
@kameyer226 it's my current understanding that active phasematching does not fit into the attune data model because the offsets are not separable. As an example, attune assumes that the offset calculated from `w1` and the offset calculated from `w2` can be added together to calculate the offset for `d1`, for any possible `w1`, `w2`, combination.

It's for this reason that @ksunden and @emkaufman developed the ndinterp daemon, which I believe is already used.

Again, this is just my understanding. I could be wrong!

**Comment by kameyer226** [comment]
The difference being that there may be more than one wrapped_daemon if an extra motor is needed for aligning a mirror kinematically during the procedure.  Mainly this issue just calls into question whether or not the phasematching should be considered an attune with some ndinterp potentially used, whereas it is my understanding that the phasematching currently stands as simply ndinterp with no attune involved.   Am I right?

**Comment by untzag** [comment]
> phasematching currently stands as simply ndinterp with no attune involved

I believe you are correct.

>  Mainly this issue just calls into question whether or not the phasematching should be considered an attune with some ndinterp potentially used.

My vote is "phasematching should not use attune". On a longer timescale perhaps the attune data model could be extended to support multidimensional correction factors, but that seems like a large amount of effort when we already have a working solution in ndinterp.

Just my vote! It's not my project, just trying to give some historical context.

**Comment by kameyer226** [comment]
I'll close this issue in a few days, is there still reason to keep ndinterp in yaqd-wright?   It seems more useful now in general after this was all brought up...

**Comment by ksunden** [comment]
ndinterp is kind of a hack, it emulates enough of the interface expected of an `attune-delay` to fool the `attune` daemon in to treating it exactly as it does delays, but most of those methods don't actually do anything.

I'm of the firm belief after dealing with cosets from PyCMDS and implementing attune-delay that these kind of domain-specific "correction" factors are much better as to-task implementations rather than trying to do something overgeneralized.

As such, I feel that there needs to be a use case in mind and not just "I want all the autonomics".
That said, I could imagine breaking out the "what does the 'control' object need to know" bits into a trait.

ndinterp is in yaqd-wright because that is kind of the catch-all for "really specific things for the wright group". 
- I would advise against anyone outside of the Wright Group using it. Thus I don't want it to be its own package.
- Its closest relatives are the attune daemons, though it does not itself use attune, so it doesn't seem right to have it here.
- So it kind of defaults to yaqd-wright at that point

**Comment by ksunden** [comment]
For context, I put ndinterp together in about a day or two so that specific experiments could be conducted. I never really looked back at it. 

I'd consider making something more specialized to the task after calibration procedures, tests of repeatability, and comparison of empirical data to theory are concluded.
